#+TITLE: Dev Docs

* About
This DBT/Mindfulness app will provide a way to track customizable skills, offer practices and provide data on progress.

It will be a web-based application. The home-screen will require the user to log into their account. They will then be able to select the date from a calendar they want to add data. It will display the skills they have chosen have displayed and they will input data. The data will be saved in the database. Users can view historical data and view the help section.

* Approach
- problem-based learning drawn from "Zero to Prod in Rust"
** User Stories
- capture the who we are building it for, the actions they want to perform, and their motives
- as a ... I want to.. so that...
1) As a user,
    I want to store my scores for multiple skills each day,
    So that I can track progress
2) As a user,
    I want to view stored scores,
    So that I can review progress
** Stack
- React with Typescript

* Linting and Formatting
** Linting
#+begin_src
cargo clippy
#+end_src
** Formatting
#+begin_src
cargo fmt
#+end_src
* Docker
** Launch Postgres server
#+begin_src shell
chmod +x scripts/init_db.sh
./scripts/init_db.sh
#+end_src

#+RESULTS:
| 304583ebb0d4808c93d620a9d679d9ff2617e643c4bcfb2b7942eb8d70791d80 |                        |        |        |        |              |              |
| Applied                                                          | 20211228003329/migrate | create | diary  | skills | table        | (2.839166ms) |
| Applied                                                          | 20211228005507/migrate | create | skills | table  | (4.995791ms) |              |
| Applied                                                          | 20211228005520/migrate | create | diary  | table  | (2.793416ms) |              |
| Applied                                                          | 20211228003329/migrate | create | diary  | skills | table        | (1.69425ms)  |
| Applied                                                          | 20211228005507/migrate | create | skills | table  | (6.040375ms) |              |
| Applied                                                          | 20211228005520/migrate | create | diary  | table  | (2.648875ms) |              |


** Kill Postgres Server
#+begin_src shell
docker kill $(docker ps -q)
#+end_src

#+RESULTS:
: c142446b208e

* Postgres
** Migrate Database
#+begin_src shell
SKIP_DOCKER=true ./scripts/init_db.sh
#+end_src

#+RESULTS:

** Seed the database
#+begin_src shell
cargo run --bin run_seeds
#+end_src

#+RESULTS:

* API
** Health Check
#+begin_src restclient
GET http://localhost:8000/health_check
#+end_src

#+RESULTS:
#+BEGIN_SRC js
// GET http://localhost:8000/health_check
// HTTP/1.1 200 OK
// content-length: 0
// date: Mon, 27 Dec 2021 20:04:15 GMT
// Request duration: 0.004877s
#+END_SRC

When running a health check we should return a 200.
#+NAME: Expected Health Check Response
#+BEGIN_SRC js
 // GET http://localhost:8000/health_check
 // HTTP/1.1 200 OK
 // content-length: 0
 // date: Thu, 30 Sep 2021 03:37:37 GMT
 // Request duration 0.029655s
#+END_SRC

#+RESULTS: Expected Health Check Response
** Diary Entries
*** Create Diary Entry
#+begin_src restclient
POST http://localhost:8000/diary_entries
Content-Type: application/json
{
"entry_date": "2021-12-30T17:53:59Z",
"skill_ids": [10, 12, 22]
}
#+end_src

#+RESULTS:
#+BEGIN_SRC js
{
  "id": 2,
  "entry_date": "2021-12-30",
  "created_at": "2022-01-14T04:10:03.581480Z"
}
// POST http://localhost:8000/diary_entries
// HTTP/1.1 201 Created
// content-length: 77
// content-type: application/json
// date: Fri, 14 Jan 2022 04:10:03 GMT
// Request duration: 0.059445s
#+END_SRC

*** Show Diary Entry by ID (Action: show)
#+begin_src restclient
GET http://localhost:8000/diary_entries/21
#+end_src

#+RESULTS:
#+BEGIN_SRC js
// GET http://localhost:8000/diary_entries/21
// HTTP/1.1 404 Not Found
// content-length: 0
// date: Thu, 06 Jan 2022 17:43:59 GMT
// Request duration: 0.025372s
#+END_SRC

*** Index Diary Entries by Date Range (Action: index)
#+begin_src restclient
GET http://localhost:8000/diary_entries
#+end_src

#+RESULTS:
#+BEGIN_SRC text
Query deserialize error: premature end of input
GET http://localhost:8000/diary_entries?start_date
HTTP/1.1 400 Bad Request
content-length: 47
content-type: text/plain; charset=utf-8
date: Sun, 16 Jan 2022 04:59:10 GMT
Request duration: 0.009263s
#+END_SRC

** Skills
*** Show Skill by ID (Action: show)
#+begin_src restclient
GET http://localhost:8000/skills/21
#+end_src

#+RESULTS:
#+BEGIN_SRC js
{
  "id": 21,
  "name": "encouragement",
  "category": "distress_tolerance"
}
// GET http://localhost:8000/skills/21
// HTTP/1.1 200 OK
// content-length: 64
// content-type: application/json
// date: Thu, 06 Jan 2022 17:44:10 GMT
// Request duration: 0.019755s
#+END_SRC

*** Retrieve all Skills (Action: index)
#+begin_src restclient
GET http://localhost:8000/skills
#+end_src
