#+TITLE: Dev Docs

* About
This DBT/Mindfulness app will provide a way to track customizable skills, offer practices and provide data on progress.

It will be a web-based application. The home-screen will require the user to log into their account. They will then be able to select the date from a calendar they want to add data. It will display the skills they have chosen have displayed and they will input data. The data will be saved in the database. Users can view historical data and view the help section.

* Approach
- problem-based learning drawn from "Zero to Prod in Rust"
** User Stories
- capture the who we are building it for, the actions they want to perform, and their motives
- as a ... I want to.. so that...
1) As a user,
    I want to store my scores for multiple skills each day,
    So that I can track progress
2) As a user,
    I want to view stored scores,
    So that I can review progress
** Strategy
- choose a web framework
- define testing strategy
- choose a crate
* Linting and Formatting
** Linting
#+begin_src
cargo clippy
#+end_src
** Formatting
#+begin_src
cargo fmt
#+end_src
* Docker
** Launch Postgres server
#+begin_src shell
chmod +x scripts/init_db.sh
./scripts/init_db.sh
#+end_src

** Kill Postgres Server
#+begin_src shell
docker kill $(docker ps -q)
#+end_src
* Postgres
** Migrate Database
#+begin_src shell
SKIP_DOCKER=true ./scripts/init_db.sh
#+end_src

* API
** Health Check
#+begin_src restclient
GET http://localhost:8000/health_check
#+end_src

When running a health check we should return a 200.
#+NAME: Expected Health Check Response
#+BEGIN_SRC js
 // GET http://localhost:8000/health_check
 // HTTP/1.1 200 OK
 // content-length: 0
 // date: Thu, 30 Sep 2021 03:37:37 GMT
 // Request duration 0.029655s
#+END_SRC

#+RESULTS: Expected Health Check Response

** Enter Data
#+begin_src shell
curl -i -X POST -d 'skill_name=mindfulness&completed=true' http://localhost:8000/enter_data
#+end_src
