#+TITLE: Dev Docs

* About
This DBT/Mindfulness app will provide a way to track customizable skills, offer practices and provide data on progress.

It will be a web-based application. The home-screen will require the user to log into their account. They will then be able to select the date from a calendar they want to add data. It will display the skills they have chosen have displayed and they will input data. The data will be saved in the database. Users can view historical data and view the help section.

* Approach
- problem-based learning drawn from "Zero to Prod in Rust"
** User Stories
- capture the who we are building it for, the actions they want to perform, and their motives
- as a ... I want to.. so that...
1) As a user,
    I want to store my scores for multiple skills each day,
    So that I can track progress
2) As a user,
    I want to view stored scores,
    So that I can review progress
** Stack
- App server: Rust with Postgres, actix
- Frontend: React with Typescript

* Linting and Formatting
** Linting
#+begin_src
cargo clippy
#+end_src
** Formatting
#+begin_src
cargo fmt
#+end_src
* Docker
** Recompile shell file
#+begin_src zsh
chmod +x scripts/init_db.sh
#+end_src

** Launch Postgres server
#+begin_src shell
./scripts/init_db.sh
#+end_src

#+RESULTS:
| 876e7465cc036820aa9c37c2b095c7b5f759a6c3b7078fd0dd0373b474fd670e |                        |        |        |        |              |              |
| Applied                                                          | 20211228003329/migrate | create | diary  | skills | table        | (1.524083ms) |
| Applied                                                          | 20211228005507/migrate | create | skills | table  | (4.1455ms)   |              |
| Applied                                                          | 20211228005520/migrate | create | diary  | table  | (2.839791ms) |              |
| Applied                                                          | 20211228003329/migrate | create | diary  | skills | table        | (1.697125ms) |
| Applied                                                          | 20211228005507/migrate | create | skills | table  | (5.485416ms) |              |
| Applied                                                          | 20211228005520/migrate | create | diary  | table  | (2.833ms)    |              |

** Kill Postgres Server
#+begin_src shell
docker kill $(docker ps -q)
#+end_src

#+RESULTS:
: 003ba494132e

* Postgres
** Migrate Database
#+begin_src shell
SKIP_DOCKER=true ./scripts/init_db.sh
#+end_src

#+RESULTS:

** Seed the database
#+begin_src shell
cargo run --bin run_seeds
#+end_src

#+RESULTS:

* API
** Health Check
#+begin_src restclient
GET http://localhost:8000/health_check
#+end_src

#+RESULTS:
: #+BEGIN_SRC js
: // GET http://localhost:8000/health_check
: // HTTP/1.1 200 OK
: // content-length: 0
: // date: Wed, 09 Feb 2022 02:45:13 GMT
: // Request duration: 0.062940s
: #+END_SRC

When running a health check we should return a 200.
#+NAME: Expected Health Check Response
#+BEGIN_SRC js
 // GET http://localhost:8000/health_check
 // HTTP/1.1 200 OK
 // content-length: 0
 // date: Thu, 30 Sep 2021 03:37:37 GMT
 // Request duration 0.029655s
#+END_SRC

#+RESULTS: Expected Health Check Response
** Diary Entries
*** Create Diary Entry
#+begin_src restclient
POST http://localhost:8000/diary_entries
Content-Type: application/json
{
  "entry_date": "2022-01-12T17:53:59Z",
  "skill_ids": [1, 5, 1]
}
#+end_src

#+RESULTS:
#+BEGIN_SRC js
{
  "id": 1,
  "entry_date": "2022-01-12",
  "created_at": "2022-02-09T02:45:47.343650Z"
}
// POST http://localhost:8000/diary_entries
// HTTP/1.1 201 Created
// content-length: 77
// content-type: application/json
// date: Wed, 09 Feb 2022 02:45:47 GMT
// Request duration: 0.059982s
#+END_SRC

*** Show Diary Entry by Date (Action: show)
#+begin_src restclient
GET http://localhost:8000/diary_entries/2022-02-06
#+end_src

#+RESULTS:
#+BEGIN_SRC js
// GET http://localhost:8000/diary_entries/2022-02-02
// HTTP/1.1 404 Not Found
// content-length: 0
// date: Sun, 20 Feb 2022 19:30:48 GMT
// Request duration: 0.019373s
#+END_SRC

*** Show Diary Entry Skills by Date (Action: show)
#+begin_src restclient
GET http://localhost:8000/diary_entries/2021-11-30/skills
#+end_src

#+RESULTS:
#+BEGIN_SRC js
[]
// GET http://localhost:8000/diary_entries/2021-11-30/skills
// HTTP/1.1 200 OK
// content-length: 2
// content-type: application/json
// date: Wed, 26 Jan 2022 05:02:51 GMT
// Request duration: 0.009779s
#+END_SRC

*** Index Diary Entries by Date Range (Action: index)
#+begin_src restclient
GET http://localhost:8000/diary_entries?start=2021-10-01&end=2022-10-20
#+end_src

#+RESULTS:
#+BEGIN_SRC js
[
  {
    "id": 1,
    "entry_date": "2021-12-30",
    "created_at": "2022-01-25T23:37:22.884289Z"
  }
]
// GET http://localhost:8000/diary_entries?start=2021-10-01&end=2022-10-20
// HTTP/1.1 200 OK
// content-length: 79
// content-type: application/json
// date: Tue, 25 Jan 2022 23:42:30 GMT
// Request duration: 0.010906s
#+END_SRC

** Skills
*** Show Skill by ID (Action: show)
#+begin_src restclient
GET http://localhost:8000/skills/21
#+end_src

#+RESULTS:
#+BEGIN_SRC js
{
  "id": 21,
  "name": "encouragement",
  "category": "distress_tolerance"
}
// GET http://localhost:8000/skills/21
// HTTP/1.1 200 OK
// content-length: 64
// content-type: application/json
// date: Thu, 06 Jan 2022 17:44:10 GMT
// Request duration: 0.019755s
#+END_SRC

*** Retrieve all Skills (Action: index)
#+begin_src restclient
GET http://localhost:8000/skills
#+end_src
