#+TITLE: Dev Docs

* About
This DBT/Mindfulness app will provide a way to track customizable skills, offer practices and provide data on progress.

It will be a web-based application. The home-screen will require the user to log into their account. They will then be able to select the date from a calendar they want to add data. It will display the skills they have chosen have displayed and they will input data. The data will be saved in the database. Users can view historical data and view the help section.

* Approach
- problem-based learning drawn from "Zero to Prod in Rust"
** User Stories
- capture the who we are building it for, the actions they want to perform, and their motives
- as a ... I want to.. so that...
1) As a user,
    I want to store my scores for multiple skills each day,
    So that I can track progress
2) As a user,
    I want to view stored scores,
    So that I can review progress
** Strategy
- choose a web framework
- define testing strategy
- choose a crate
** To do
- define struct for skills table
- fix return type for insert_entry fn, should not be a string until it needs to be
- need to wrap get_data in another function (as it currently returns HttpResponse or sqlx error, don't want to leak internal )
* Linting and Formatting
** Linting
#+begin_src
cargo clippy
#+end_src
** Formatting
#+begin_src
cargo fmt
#+end_src
* Docker
** Launch Postgres server
#+begin_src shell
chmod +x scripts/init_db.sh
./scripts/init_db.sh
#+end_src

#+RESULTS:
| e278d35bea0374593b476e5c7cede15b058169d07f6f4af8569550aa8b783f0a |                        |        |        |        |              |              |
| Applied                                                          | 20211228003329/migrate | create | diary  | skills | table        | (1.659541ms) |
| Applied                                                          | 20211228005507/migrate | create | skills | table  | (4.430125ms) |              |
| Applied                                                          | 20211228005520/migrate | create | diary  | table  | (2.990083ms) |              |
| Applied                                                          | 20211228003329/migrate | create | diary  | skills | table        | (1.706875ms) |
| Applied                                                          | 20211228005507/migrate | create | skills | table  | (6.221875ms) |              |
| Applied                                                          | 20211228005520/migrate | create | diary  | table  | (3.238583ms) |              |


** Kill Postgres Server
#+begin_src shell
docker kill $(docker ps -q)
#+end_src

#+RESULTS:
: 98dfe34b68e2

* Postgres
** Migrate Database
#+begin_src shell
SKIP_DOCKER=true ./scripts/init_db.sh
#+end_src

#+RESULTS:

* API
** Health Check
#+begin_src restclient
GET http://localhost:8000/health_check
#+end_src

#+RESULTS:
#+BEGIN_SRC js
// GET http://localhost:8000/health_check
// HTTP/1.1 200 OK
// content-length: 0
// date: Mon, 27 Dec 2021 20:04:15 GMT
// Request duration: 0.004877s
#+END_SRC

When running a health check we should return a 200.
#+NAME: Expected Health Check Response
#+BEGIN_SRC js
 // GET http://localhost:8000/health_check
 // HTTP/1.1 200 OK
 // content-length: 0
 // date: Thu, 30 Sep 2021 03:37:37 GMT
 // Request duration 0.029655s
#+END_SRC

#+RESULTS: Expected Health Check Response

** Enter Data
#+begin_src restclient
POST http://localhost:8000/create
Content-Type: application/json
{
"name": "mindfulness",
"completed": true
}
#+end_src

#+RESULTS:
#+BEGIN_SRC js
{
  "id": "51d7ea5e-95f5-4782-8653-0b90f5354526",
  "name": "mindfulness",
  "completed": true,
  "created_at": "2021-12-27T22:35:13.755543Z"
}
// POST http://localhost:8000/create
// HTTP/1.1 201 Created
// content-length: 126
// content-type: application/json
// date: Mon, 27 Dec 2021 22:35:13 GMT
// Request duration: 0.030315s
#+END_SRC

** GET Data
#+begin_src restclient
GET http://localhost:8000/show/51d7ea5e-95f5-4782-8653-0b90f5354526
#+end_src

#+RESULTS:
#+BEGIN_SRC js
{
  "id": "51d7ea5e-95f5-4782-8653-0b90f5354526",
  "name": "mindfulness",
  "completed": true,
  "created_at": "2021-12-27T22:35:13.755543Z"
}
// GET http://localhost:8000/show/51d7ea5e-95f5-4782-8653-0b90f5354526
// HTTP/1.1 200 OK
// content-length: 126
// content-type: application/json
// date: Mon, 27 Dec 2021 22:36:32 GMT
// Request duration: 0.020039s
#+END_SRC
