-- INSERT INTO skills (name, category)
--        VALUES
--        ('describe', 'mindfulness'),
--        ('participate', 'mindfulness'),
--        ('non-judgmentally', 'mindfulness'),
--        ('one-mindfully', 'mindfulness'),
--        ('effectively', 'mindfulness'),
--        ('activities', 'distress_tolerance'),
--        ('contributing', 'distress_tolerance'),
--        ('comparisons', 'distress_tolerance'),
--        ('opposite_emotions', 'distress_tolerance'),
--        ('pushing_away', 'distress_tolerance'),
--        ('thoughts', 'distress_tolerance'),
--        ('sensations', 'distress_tolerance'),
--        ('self-soothe', 'distress_tolerance'),
--        ('imagery', 'distress_tolerance'),
--        ('meaning', 'distress_tolerance'),
--        ('prayer', 'distress_tolerance'),
--        ('relaxation', 'distress_tolerance'),
--        ('one_thing', 'distress_tolerance'),
--        ('vacation', 'distress_tolerance'),
--        ('encouragement', 'distress_tolerance'),
--        ('pros_and_cons', 'distress_tolerance'),
--        ('accepting_reality', 'distress_tolerance'),
--        ('willingness', 'distress_tolerance'),
--        ('turning_the_mind', 'distress_tolerance'),
--        ('radical_acceptance', 'distress_tolerance'),
--        ('treat_physical_illness', 'emotion_regulation'),
--        ('eating', 'emotion_regulation'),
--        ('altering_drugs', 'emotion_regulation'),
--        ('sleep', 'emotion_regulation'),
--        ('exercise', 'emotion_regulation'),
--        ('build_mastery', 'emotion_regulation'),
--        ('positive_experiences', 'emotion_regulation'),
--        ('mindful_of_current_emotion', 'emotion_regulation'),
--        ('opposite_action', 'emotion_regulation');

INSERT INTO skills (name, category, description)
       VALUES
       ('observe', 'mindfulness', 'observe description'),
       ('positive_experiences', 'emotion_regulation', 'positive experiences description'),
       ('encouragement', 'distress_tolerance', 'you got this!');
