# Security Audit on Push
# https://github.com/actions-rs/audit-check
# This GitHub Action is using cargo-audit to perform an audit for crates with security vulnerabilities.

name: Security audit
on:
  push:
    paths: 
      - '**/Cargo.toml'
      - '**/Cargo.lock'
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
